Name:           ros-indigo-dynamixel-driver
Version:        0.4.0
Release:        0%{?dist}
Summary:        ROS dynamixel_driver package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/dynamixel_driver
Source0:        %{name}-%{version}.tar.gz

Requires:       pyserial
Requires:       ros-indigo-diagnostic-msgs
Requires:       ros-indigo-rospy
BuildRequires:  ros-indigo-catkin

%description
This package provides low level IO for Robotis Dynamixel servos. Fully supports
and was tested with AX-12, AX-18, RX-24, RX-28, MX-28, RX-64, EX-106 models.
Hardware specific constants are defined for reading and writing information
from/to Dynamixel servos. This low level package won't be used directly by most
ROS users. The higher level dynamixel_controllers and specific robot joint
controllers make use of this package.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Dec 21 2014 Antons Rebguns <arebgun@gmail.com> - 0.4.0-0
- Autogenerated by Bloom

